// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwelhhxaqaiagqdcxfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd2VsaGh4YXFhaWFncWRjeGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTgzMjksImV4cCI6MjA3MjA3NDMyOX0.Hc9eYmgxoTRTToUgAt9aKJ2zn7aSmMjvUSC83dNs7EQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});