// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvipkkjmzcinqfvjntna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aXBra2ptemNpbnFmdmpudG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTUxMjUsImV4cCI6MjA2NjE5MTEyNX0.wtA51Xl8bA2K_bh9bKZerOuoJDvNKl1rQqxXWH76hyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});